### ISSUE TITLE
rebuild for NZZ data

### ISSUE THREAD

**Issue by simon-clematide** [impresso/impresso-pycommons#24] opened 2018-11-16 16:28 UTC
@mromanello 
My tests on 1780/1781 which are on s3 raise errors
```
$ cat config.nzz.json
[{
        "NZZ": [1780, 1781]
    }
]
$ python rebuilder.py rebuild_articles --input-bucket=original-canonical-data --output-dir=out.d  --log-file=out.err --filter-config=config.nzz.json --format=solr --verbose

Processing batch 1/1 [{'NZZ': [1780, 1781]}]
Processing year 1780
Retrieving issues...
Detecting items for NZZ for years ['NZZ/1780']
[########################################] | 100% Completed |  0.1s
()
Traceback (most recent call last):
  File "rebuilder.py", line 489, in <module>
    main()
  File "rebuilder.py", line 474, in main
    format=output_format
  File "rebuilder.py", line 359, in rebuild_issues
    issue = IssueDir(**issues[0])
IndexError: tuple index out of range
```

**Comment by simon-clematide** [comment] 2018-11-16 16:34
@mromanello maybe I tried something the wrong way, maybe you can test it. I'm reluctant to upload more canonical data right now because deleting everything would be another hour...
The dask code where everything is compiled into an expression makes debugging a bit difficult.
 I would like  to use/test the core functionality of the rebuild by something as simple as:

- given an issue json, locally produce a rebuilt version

Right now, although this would be a simple test, this cannot be easily done. s3 and dask make simple things a bit cumbersome.

**Comment by simon-clematide** [comment] 2018-11-16 16:39
I tested on master, but now also tested on new-s3-reading branch. Also not working

**Comment by mromanello** [comment] 2018-11-16 16:41
The error you see

> issue = IssueDir(**issues[0])

it's because the function `impresso_iter_bucket` cannot detect any issue on S3. It's actually a step before rebuilding.

**Comment by mromanello** [comment] 2018-11-16 16:43
I tested with 

```
issues = impresso_iter_bucket(
    'original-canonical-data',
    prefix="NZZ/1780",
    item_type="issue"
)
```

and also does not find any issue.

**Comment by simon-clematide** [comment] 2018-11-16 19:18
Seems that the impresso_iter_bucket code relies on keys that my uploaded content does not provide:
```
--> 501                         raise_exception(exc, tb)
    502                 res, worker_id = loads(res_info)
    503                 state['cache'][key] = res

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/dask/compatibility.py in reraise(exc, tb)
    109     def reraise(exc, tb=None):
    110         if exc.__traceback__ is not tb:
--> 111             raise exc.with_traceback(tb)
    112         raise exc
    113

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/dask/local.py in execute_task()
    270     try:
    271         task, data = loads(task_info)
--> 272         result = _execute_task(task, data)
    273         id = get_id()
    274         result = dumps((result, id))

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/dask/local.py in _execute_task()
    251         func, args = arg[0], arg[1:]
    252         args2 = [_execute_task(a, cache) for a in args]
--> 253         return func(*args2)
    254     elif not ishashable(arg):
    255         return arg

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/dask/bag/core.py in reify()
   1560 def reify(seq):
   1561     if isinstance(seq, Iterator):
-> 1562         seq = list(seq)
   1563     if seq and isinstance(seq[0], Iterator):
   1564         seq = list(map(list, seq))

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/dask/bag/core.py in map_chunk()
   1720     else:
   1721         for a in zip(*args):
-> 1722             yield f(*a)
   1723
   1724     # Check that all iterators are fully exhausted

/mnt/storage/karr/projects/climpresso/nzz/impresso-pycommons/tests/src/impresso-commons/impresso_commons/path/path_s3.py in _process_keys()
    150     build = _key_to_issue if item_type == "issue" else _key_to_contentitem
    151     # retrieve versioning information
--> 152     version_id, last_modified = get_s3_versions(bucket_name, key_name)[0]
    153     # return the object, using the appropriate function
    154     return build((key_name, version_id, last_modified))

/mnt/storage/karr/projects/climpresso/nzz/impresso-pycommons/tests/src/impresso-commons/impresso_commons/utils/s3.py in get_s3_versions()
    278             v.get().get('LastModified')
    279         )
--> 280         for v in versions
    281     ]
    282     return version_ids

/mnt/storage/karr/projects/climpresso/nzz/impresso-pycommons/tests/src/impresso-commons/impresso_commons/utils/s3.py in <listcomp>()
    278             v.get().get('LastModified')
    279         )
--> 280         for v in versions
    281     ]
    282     return version_ids

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/boto3/resources/factory.py in do_action()
    518             # instance via ``self``.
    519             def do_action(self, *args, **kwargs):
--> 520                 response = action(self, *args, **kwargs)
    521
    522                 if hasattr(self, 'load'):

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/boto3/resources/action.py in __call__()
     81                     operation_name, params)
     82
---> 83         response = getattr(parent.meta.client, operation_name)(**params)
     84
     85         logger.debug('Response: %r', response)

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/botocore/client.py in _api_call()
    318                     "%s() only accepts keyword arguments." % py_operation_name)
    319             # The "self" in this scope is referring to the BaseClient.
--> 320             return self._make_api_call(operation_name, kwargs)
    321
    322         _api_call.__name__ = str(py_operation_name)

/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/botocore/client.py in _make_api_call()
    621             error_code = parsed_response.get("Error", {}).get("Code")
    622             error_class = self.exceptions.from_code(error_code)
--> 623             raise error_class(parsed_response, operation_name)
    624         else:
    625             return parsed_response

ClientError: An error occurred (NoSuchKey) when calling the GetObject operation: Unknown
```

**Comment by e-maud** [comment] 2018-11-16 20:30
Hello, key in impresso_iter_bucket are S3 keys, I can have a look tomorrow.

**Comment by simon-clematide** [comment] 2018-11-16 22:03
Hmmh, I am not very happy that our main processing pipeline has pretty strong hard-coded dependencies on s3 storage, even more specifically on versioned ones. Where to store/fetch stuff should ideally be something which can be selected by a switch outside. Additionally, versions in s3 seem to have quite weak tooling built around them (my beloved s3cmd tool seems to be especially weak, for quite some time). Simple things like restoring to a version needs to be programmed if my investigations are correct.I fear a bit that we overcomplicate things and complicate testing, debugging for future development considerably.

**Comment by mromanello** [comment] 2018-11-17 08:43
It seems quite clear to me that the issue is with s3cmd which does not know how to write to a versioned bucket.

For the time being, you can use the CLI script that I use to upload the canonical JSON data. You find it at [text_importer.upload](https://github.com/impresso/impresso-text-acquisition/blob/master/text_importer/upload.py). This script detects your local canonical issues and uploads them to s3.

**Comment by e-maud** [comment] 2018-11-17 10:35
Reading from S3 was so far our main and only frame and there was not time nor need up to now for smthg else. However it would indeed be possible to decouple I/O from main processes with 1. a new function which reads from somewhere else (with same signature and outputting `IssueDir`) and 2. a switch mechanism outside. Which raises again the point of uniforming parameter handling.... - topic on the radar since few weeks, will open an issue!

**Comment by mromanello** [comment] 2018-11-17 10:56
Having a double mechanism for I/O for the rebuild (read/write from/to local storage as well as s3) was considered but not implemented as it’s something that may make some sense but I could not afford (time- and priority-wise).

**Comment by simon-clematide** [comment] 2018-11-18 08:44
> It seems quite clear to me that the issue is with s3cmd which does not know how to write to a versioned bucket.
> 
> For the time being, you can use the CLI script that I use to upload the canonical JSON data. You find it at [text_importer.upload](https://github.com/impresso/impresso-text-acquisition/blob/master/text_importer/upload.py). This script detects your local canonical issues and uploads them to s3.

Thanks for the hint. I will adapt it (I cannot use it directly because it assumes the hard-coded KNOWN_JOURNALS which does not contain NZZ.)

**Comment by simon-clematide** [comment] 2018-11-18 08:46
> Having a double mechanism for I/O for the rebuild (read/write from/to local storage as well as s3) was considered but not implemented as it’s something that may make some sense but I could not afford (time- and priority-wise).

I can fully understand the reasons behind it, it just makes it difficult if the setup is not 100% the same.

**Comment by e-maud** [comment] 2018-11-19 09:45
Ok, thanks a lot for these hints! So far we were only overwriting and not deleting individual keys (only buckets), this is why we never encountered this case, but it's good to make things more robust.

What about you do the last change you proposed, and run the test?
We've put a test function in `tests` that you can use with this command (you need `py-test` installed, which is a dev dependency of pycommons specified in the `Pipfile`).

`pytest -s -vv tests/test_utils_s3.py::test_utils_s3.py`

`-s` : print on sdtout
`-vv`: verbose

If everything goes well please feel free to just push, increasing the version from `0.6.5` to `0.6.6` in `impresso_commons/__init__.py`. Thanks!

**Comment by simon-clematide** [comment] 2018-11-19 10:15
The test command fails in a fresh installation:
```
$ pytest -s -vv tests/test_utils_s3.py::test_utils_s3.py
Traceback (most recent call last):
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/_pytest/config/__init__.py", line 381, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/test_utils_s3.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/_pytest/config/__init__.py", line 381, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/storage/karr/projects/climpresso/impresso-pycommons/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/_pytest/config/__init__.py", line 412, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/_pytest/config/__init__.py", line 418, in _importconftest
    mod = conftestpath.pyimport()
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 290, in load_module
    six.exec_(co, mod.__dict__)
  File "/mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/conftest.py", line 15, in <module>
    handler = logging.FileHandler(filename=log_file, mode='w')
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/impresso_commons/data/logs/tests.log'
ERROR: could not load /mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/conftest.py
```
Why would a test rely on an installed version?


Then after creating this directories:
```
$ mkdir -p /mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/lib/python3.6/site-packages/impresso_commons/data/logs/
siclemat@vigrid:/mnt/storage/karr/projects/climpresso/impresso-pycommons
$ pytest -s -vv tests/test_utils_s3.py::test_utils_s3.py
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.6.5, pytest-3.8.1, py-1.7.0, pluggy-0.8.0 -- /mnt/storage/clfiles/resources/applications/toolkit/anaconda/3-v5.2.0/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/mnt/storage/karr/projects/climpresso/impresso-pycommons/.hypothesis/examples')
rootdir: /mnt/storage/karr/projects/climpresso/impresso-pycommons, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2, hypothesis-3.82.1
collecting 0 items
========================================================================================= no tests ran in 0.50 seconds ==========================================================================================
ERROR: not found: /mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/test_utils_s3.py::test_utils_s3.py
(no name '/mnt/storage/karr/projects/climpresso/impresso-pycommons/tests/test_utils_s3.py::test_utils_s3.py' in any of [<Module 'tests/test_utils_s3.py'>])
```

**Comment by e-maud** [comment] 2018-11-19 10:18
Sorry my mistake, the command should be:

`pytest -s -vv tests/test_utils_s3.py::test_get_s3_versions`

**Comment by simon-clematide** [comment] 2018-11-19 11:42
Updated and pushed, and the collection phase of the issues now runs through. However, the rebuild still throws the same kind of exceptions. Will investigate later.

**Comment by mromanello** [comment] 2018-11-19 11:51
(concerning the rebuild still throwing exceptions: note that you'll need to manually update the pycommons library – I usually do uninstall/new install. It happened to me a few times to forget that... ;-( )

**Comment by mromanello** [comment] 2018-11-22 13:33
this can be closed as the only pending issue is [this](https://github.com/impresso/nzz/issues/6) but that's on the data side rather than on the rebuild code side.

**Closed by mromanello** 2018-11-22 13:33 UTC
